import type { Preview } from "@/lib/analysis/analysis-types";
import { fmtInt, fmtMinutes, fmtPct, fmtRange } from "@/lib/format";
export function PreviewHeading({ preview: p, sample = false }: { preview: Preview; sample?: boolean }) {
  return <header className="reader-preview-heading"><span className="v3-tag">{sample ? "Sample · fictional conversation" : "Your free preview"}</span><span className="reader-emoji" aria-hidden="true">💌</span><h1>Let’s look at the whole picture.</h1><p>{fmtInt(p.totalMessages)} messages{!p.liteMode && <> · {fmtRange(p.range)}</>}</p></header>;
}
export function PreviewSection({ preview: p, compact = false }: { preview: Preview; compact?: boolean }) {
  if (compact) return <p className="report-meta">{fmtInt(p.totalMessages)} messages{!p.liteMode && <> · {fmtRange(p.range)}</>}</p>;
  const comparison = !p.liteMode ? p.headline?.comparison : undefined;
  return <section className="reader-free" aria-label="Your free findings"><h2>{p.liteMode ? "Every conversation has a rhythm. Here’s a first look at yours." : p.headline?.sentence ?? "No sharp change stands out in the available messages."}</h2><p>{p.liteMode ? "Without timestamps, we can look at how you share the conversation, but not how quickly you reply or when things changed." : comparison ? "These two behaviors help put the change in context. They describe the conversation, not what he feels." : "Start with how often he reaches out and how long his replies typically take. Consistency needs context too."}</p><dl className="reader-preview-metrics"><div><dt>{p.liteMode ? "His message share" : "He starts chats"}</dt><dd>{comparison ? <>{fmtPct(comparison.initiation.before)} <i>→</i> {fmtPct(comparison.initiation.after)}</> : fmtPct(p.liteMode ? p.messageShare.him : p.initiation.him)}</dd><small>{comparison ? "Before → after the change" : `You: ${fmtPct(p.liteMode ? p.messageShare.you : p.initiation.you)}`}</small></div><div><dt>{p.liteMode ? "His messages with questions" : "His typical reply"}</dt><dd>{p.liteMode ? fmtPct(p.questionRatio.him) : comparison ? <>{fmtMinutes(comparison.reply.before)} <i>→</i> {fmtMinutes(comparison.reply.after)}</> : fmtMinutes(p.medianReply.him)}</dd><small>{comparison ? "Before → after the change" : `You: ${p.liteMode ? fmtPct(p.questionRatio.you) : fmtMinutes(p.medianReply.you)}`}</small></div></dl></section>;
}
