import type { QuestionId } from "@/lib/questions";

export interface ChatScene {
  slug: string;
  title: string;
  question: QuestionId;
  note: string;
  messages: readonly (readonly ["You" | "Him", string])[];
}

export const CHAT_SCENES: readonly ChatScene[] = [
  { slug: "talking-stage", title: "Talking stage", question: "likes_me", note: "He sounds pleased to hear from you. A longer chat can show whether he reaches out too.", messages: [["You", "Had fun tonight :)"], ["Him", "me too, still laughing about the waiter"], ["You", "We should do it again"], ["Him", "definitely"], ["You", "Are you free Friday?"]] },
  { slug: "first-dates", title: "First dates", question: "likes_me", note: "He suggests a time and makes a booking. That's a concrete plan you can respond to.", messages: [["Him", "Thursday at 7?"], ["Him", "Found a place I think you'd like"], ["You", "The pasta place you mentioned?"], ["Him", "yes! booked us a table"], ["You", "Okay, looking forward to it :)"]] },
  { slug: "situationship", title: "Situationship", question: "situationship", note: "He says he misses you, but you still don't have a day to meet. Whether this repeats matters.", messages: [["Him", "miss you"], ["You", "I'd like to see you too"], ["You", "When are you free?"], ["Him", "this week is a lot"], ["Him", "soon though"], ["You", "Let me know a day that works"]] },
  { slug: "long-distance", title: "Long distance", question: "energy_changed", note: "You suggest a call and he makes time for it. Look at whether that happens regularly.", messages: [["You", "Made it home?"], ["Him", "just landed"], ["You", "Call after you've eaten?"], ["Him", "yes, give me 20?"], ["Him", "want to hear about your day"], ["You", "I'll put the kettle on :)"]] },
  { slug: "mixed-signals", title: "Mixed signals", question: "mixed_signals", note: "The compliment is warm. The weekend plan is still unresolved. Those are separate things to notice.", messages: [["Him", "you looked amazing btw"], ["You", "thank you :)"], ["You", "Are we still on for Saturday?"], ["Him", "might have to work"], ["You", "Sunday instead?"], ["Him", "let me check"]] },
  { slug: "reconnecting", title: "An ex reaches out", question: "ex_came_back", note: "An old memory starts the conversation. You can ask what would be different before deciding to try again.", messages: [["Him", "hey, been thinking about you"], ["You", "Hey. How have you been?"], ["Him", "good. I miss talking to you"], ["You", "What made you reach out?"], ["Him", "walked past our coffee place today"], ["You", "What would be different this time?"]] },
  { slug: "everyday-care", title: "Everyday care", question: "overview", note: "He remembers something that matters to you and asks about it. Small check-ins can be part of a consistent pattern.", messages: [["Him", "How did the presentation go?"], ["You", "I survived haha"], ["Him", "knew you would"], ["You", "Thanks for checking in"], ["Him", "Tell me about it over dinner?"]] },
  { slug: "making-time", title: "Making time", question: "likes_me", note: "He can't meet tonight, but offers another time. Being busy can still leave room for making plans together.", messages: [["You", "Free tonight?"], ["Him", "Still at work, sorry"], ["Him", "But I'm free Sunday afternoon"], ["You", "Coffee at 3?"], ["Him", "Perfect. I'll meet you there"]] },
  { slug: "who-texts-first", title: "Who texts first", question: "more_invested", note: "You're asking the questions here. The wider conversation helps show whether this is typical.", messages: [["You", "Hey, how was your weekend?"], ["Him", "good! yours?"], ["You", "Pretty quiet"], ["You", "Did you finish that show?"], ["Him", "yeah it was great"], ["You", "I'd like you to reach out sometimes too"]] },
  { slug: "cancelled-plans", title: "Cancelled plans", question: "mixed_signals", note: "A cancellation can happen for many reasons. Notice whether he helps rearrange, especially if it keeps happening.", messages: [["You", "Still good for the movie?"], ["Him", "I'm sorry, can't make it"], ["You", "Everything okay?"], ["Him", "just a lot going on"], ["You", "Want to pick another day?"], ["Him", "I'll let you know"]] },
  { slug: "after-the-date", title: "After the date", question: "likes_me", note: "He checks you got home and suggests seeing you again. You have a specific invitation to build on.", messages: [["Him", "Home safe?"], ["You", "Yep, just got in"], ["Him", "I had a really good time"], ["You", "Me too :)"], ["Him", "That walk you mentioned, next weekend?"], ["You", "I'd love that"]] },
  { slug: "where-we-stand", title: "Where we stand", question: "situationship", note: "You've said what you're looking for. The next conversation gives you both a chance to be clearer.", messages: [["You", "Can I ask you something?"], ["Him", "of course"], ["You", "What are you looking for with us?"], ["Him", "I like spending time with you"], ["You", "I do too. I'm looking for a relationship"], ["Him", "Can we talk about it tonight?"]] },
];
