import type { QuestionId } from "@/lib/questions";

export type GuideSection = { heading: string; paragraphs: string[]; items?: string[]; messages?: string[]; table?: { headings: string[]; rows: string[][] } };
export type Guide = {
  slug: string; keyword: string; title: string; description: string; category: string;
  intro: string; sections: GuideSection[]; faq: { q: string; a: string }[];
  related: string[]; question: QuestionId; cta: string;
  sources?: { title: string; url: string }[];
};
export const GUIDES_UPDATED = "2026-09-25";
export const GUIDE_CATEGORIES = ["Texting patterns", "Better conversations", "Understand the relationship", "Exes & uncertainty"];
const boundaries = { title: "love is respect: Boundaries and expectations", url: "https://www.loveisrespect.org/resources/boundaries-expectations/" };
const bombing = { title: "love is respect: Signs of love bombing", url: "https://www.loveisrespect.org/resources/signs-of-love-bombing/" };
const s = (heading: string, paragraphs: string[], items?: string[], messages?: string[]): GuideSection => ({ heading, paragraphs, items, messages });
export const GUIDES: Guide[] = [
  {
    slug: "texting-styles", keyword: "texting styles", title: "Texting Styles: Understand Your Different Chat Habits",
    description: "Compare texting styles with message examples. Understand short replies, bursts of messages and different rhythms without treating them as proof of feelings.",
    category: "Texting patterns", question: "overview", cta: "Explore your own texting patterns",
    intro: "Texting styles are the habits people bring to a conversation: how much they write, when they answer, what they share and who starts things. Different styles can create friction even when two people enjoy each other. Look at how the conversation works for both of you, rather than assigning a personality type from a few texts.",
    sections: [
      { heading: "Which habits are you noticing?", paragraphs: ["These are descriptions, not fixed categories. Someone can send practical one-line replies at work and long, thoughtful messages later. Compare similar situations before deciding a change means something."], table: { headings: ["Habit", "What it can look like", "What to check"], rows: [["Brief and practical", "‘Sounds good. Saturday at 6?’", "Do they follow through and show interest in person?"], ["Several messages at once", "A story arrives in five separate bubbles.", "Count conversation turns, not just message totals."], ["Thoughtful but delayed", "A detailed reply after an evening offline.", "Is the rhythm predictable and comfortable for you?"], ["Frequent check-ins", "Small updates throughout the day.", "Are replies welcomed or expected immediately?"], ["Media-led", "Photos and voice notes instead of paragraphs.", "A text-only view may miss much of the interaction."]] } },
      s("Separate a different style from a change in effort", ["Compare the person with their own usual behavior. A partner who has always preferred calls is different from someone who suddenly stops following up, asking questions and making plans. No single metric settles the difference.", "Also look at your contribution. If one person sends six short messages for every long reply, message share can look unequal while both people are engaged. Work schedules, accessibility needs, language and time zones all affect the pattern."]),
      s("Agree on a rhythm you can both live with", ["Name the practical issue instead of labeling the other person a bad texter. Ask for one manageable change, then see whether it helps. You can agree on an evening call without requiring constant access to each other."], undefined, ["I like hearing from you, but I can't keep up during work. Want to catch up after dinner?", "When plans are still open, could you let me know by the afternoon? I don't need instant replies otherwise."]),
      s("Use your chat history as context", ["Look at [who starts your conversations](/who-texts-first), [typical reply times](/reply-time-calculator) and whether questions receive meaningful answers. Check several ordinary weeks rather than an unusual day. If your pasted messages have no timestamps, timing and trends cannot be measured reliably.", "A [WhatsApp chat analyzer](/whatsapp-relationship-analyzer) like WhatHeThinks can organize supported chat data into patterns. It does not diagnose a texting personality or tell you what someone privately feels. Use the observations to prepare a conversation, not to win an argument."]),
    ],
    faq: [{ q: "Can different texting styles work together?", a: "Yes, if both people can agree on contact and planning that suit them. The useful question is whether your needs can be discussed and accommodated." }, { q: "Are short replies always a bad sign?", a: "No. A short reply that answers the question or confirms a plan can be useful. Repeatedly avoiding every topic is a different pattern." }, { q: "Can a texting style change?", a: "Yes. Context, familiarity and preferences can change. Ask about the shift rather than assuming its cause." }],
    related: ["dry-texting", "who-texts-first", "reply-time-calculator", "is-he-losing-interest"],
  },
  {
    slug: "questions-to-ask-your-boyfriend", keyword: "questions to ask your boyfriend", title: "Questions to Ask Your Boyfriend, With Follow-Up Ideas",
    description: "Find questions to ask your boyfriend about everyday life, memories, support and your future, with follow-ups that make the conversation feel natural.",
    category: "Better conversations", question: "overview", cta: "Reflect on your conversations together",
    intro: "The best questions to ask your boyfriend leave room for an answer you did not expect. Pick one that fits the moment, listen, and share your own answer too. This is a menu for getting to know each other, not an interview to complete in one evening.",
    sections: [
      s("Start with an ordinary day", ["Use these when you want more than ‘How was work?’ without opening a serious discussion. Follow a detail he mentions instead of immediately reaching for another question."], ["What was the best ten minutes of your day?", "What small thing annoyed you more than it should have?", "What have you been looking forward to this week?", "What would you do with an unexpectedly free afternoon?", "What's something you wish people asked you about?", "What have you changed your mind about recently?"], ["You said that meeting went well. What made it different this time?"]),
      s("Ask about memories and the person behind them", ["Let him decide how personal to get. A light memory can lead to a meaningful story without requiring a disclosure about a painful experience."], ["What did you love doing before you were good at it?", "Who made you feel understood growing up?", "What place would you like to take me back to?", "What is a family habit you want to keep?", "Which friendship taught you something important?", "What is a small achievement you're still proud of?"], ["What do you think you liked most about being there?"]),
      s("Learn what support looks like for him", ["Ask during a calm moment, not as a demand in the middle of an argument. His answer may differ from what comforts you. Share what works for you and look for something you can both offer."], ["When you're overwhelmed, do you prefer company or time alone?", "How can I tell when you want advice rather than a listener?", "What makes an apology feel meaningful to you?", "What kind of check-in feels caring, and what feels like pressure?", "Is there something I do that helps more than I realize?", "How should we let each other know we need a pause?"], ["I tend to offer solutions quickly. Would you rather I ask first?"]),
      s("Talk about the future without turning it into a test", ["Choose questions that match the stage of your relationship. Curiosity about the next month does not need to become a demand for lifelong certainty. Where a decision matters to you, ask directly rather than hiding it inside a hypothetical."], ["What would you like us to make more time for?", "How do you picture a good ordinary weekend together?", "Which routines would you want to keep if we lived together?", "How do you like to handle shared plans and expenses?", "What does commitment mean to you at this stage?", "Is there something about our expectations we should talk through?"], ["For me, commitment includes making plans we can count on. What would you add?"]),
      s("Make room for a real answer", ["Put the list away once a conversation gets going. Ask ‘What was that like?’ or share a related story of your own. If he does not want to answer, move on; openness works better when it is a choice.", "If a question reveals an ongoing disagreement, arrange a separate conversation about it. A date-night question should not quietly become a scorecard. For a structured discussion about the relationship, use these [relationship check-in questions](/relationship-check-in-questions)."]),
    ],
    faq: [{ q: "What can I ask a new boyfriend?", a: "Start with interests, everyday preferences and stories he enjoys telling. Let more personal subjects develop with trust rather than following a timetable." }, { q: "What if his answers are short?", a: "Try a concrete follow-up, offer your own answer or choose another time. One short conversation does not establish a lack of interest." }, { q: "Should I send the whole list?", a: "One question usually leaves more room for a natural exchange. You can also each choose a question and take turns." }],
    related: ["conversation-starters-for-couples", "relationship-check-in-questions", "texting-styles"],
  },
  {
    slug: "dry-texting", keyword: "dry texting", title: "Dry Texting: Examples, Possible Reasons and How to Reply",
    description: "See what dry texting looks like, how it differs from a busy reply, and ways to respond without carrying the entire conversation yourself.",
    category: "Texting patterns", question: "energy_changed", cta: "Look at how your conversation changed",
    intro: "Dry texting usually means replies that give the conversation little to work with: brief answers, few details and little follow-up. It describes an exchange, not a proven lack of interest. A useful short answer and a repeated dead end can look similar when you remove the context.",
    sections: [
      { heading: "Short is not always dry", paragraphs: ["Ask whether the reply does the job the message invited it to do. A confirmation can be one word. A personal story often invites more engagement."], table: { headings: ["You send", "Reply", "What to notice"], rows: [["‘Are we still on for 7?’", "‘Yep!’", "Brief, but answers the question."], ["‘I finally finished that project. I'm so relieved.’", "‘Cool.’", "Little to build on, especially if this repeats."], ["‘How was your weekend?’", "‘Busy. Tell you tonight?’", "A pause with an invitation to reconnect."], ["‘Would you like to meet again?’", "‘Maybe lol.’", "The issue is an unclear plan, not message length."]] } },
      s("Look for a pattern before explaining it", ["Work, tiredness, a preference for calls or not knowing what to say can all produce short replies. So can a lack of interest. You cannot distinguish those explanations from the word ‘okay’ alone.", "Notice whether he returns to the conversation, remembers what you told him and makes time elsewhere. If the warmth used to be mutual and several behaviors have changed, it is reasonable to ask about the change. Our guide to [signs he is losing interest](/is-he-losing-interest) covers which changes are worth comparing."]),
      s("Give the conversation one useful opening", ["Try a specific topic instead of sending more versions of ‘How are you?’ Share something yourself so the other person has a detail to respond to. You do not need to perform endlessly to keep someone engaged."], undefined, ["You were trying that new place today—worth going back?", "I have a story about the most chaotic part of my day. Better on a call if you're free later."]),
      s("If you keep doing all the work", ["Name your experience calmly. A question about preferences gives you more information than deliberately matching their reply time. If you are unsure whether you really do most of the work, [check who texts first](/who-texts-first) across several ordinary weeks. If the person says they are not interested, take the answer seriously rather than searching for a hidden meaning."], undefined, ["I enjoy talking with you, but lately it feels like I'm keeping the conversation going. Would you prefer calls, or are you not feeling this?"]),
    ],
    faq: [{ q: "Is ‘lol’ a dry text?", a: "It depends. It can be an appropriate reaction to a joke. If every attempt to start a conversation ends there, the overall exchange may feel one-sided." }, { q: "Should I double text a dry texter?", a: "A relevant follow-up is fine. Repeated messages cannot create mutual interest, so pay attention to whether the other person contributes." }, { q: "Can someone like me and still text briefly?", a: "Yes. Look at direct communication, follow-through and your experience together rather than treating length as a feelings score." }],
    related: ["texting-styles", "left-on-read", "how-to-keep-a-conversation-going", "is-he-losing-interest"],
  },
  {
    slug: "conversation-starters-for-couples", keyword: "conversation starters for couples", title: "Conversation Starters for Couples Who Want to Reconnect",
    description: "Try conversation starters for couples with turn-taking activities, playful prompts and gentle ways to reconnect after a busy week.",
    category: "Better conversations", question: "overview", cta: "Explore the rhythm of your conversations",
    intro: "Conversation starters for couples work best when both people get a turn. Choose an activity that fits your energy, put distractions aside if you can, and let either person pass. The point is to share a little of your world, not to prove how well you know each other.",
    sections: [
      s("A ten-minute catch-up", ["Each person chooses one prompt. Listen without fixing the problem, then ask whether your partner wants ideas or simply company. Swap roles before the time is up."], ["What took more energy than you expected today?", "What felt easier because someone helped?", "What small thing would make tomorrow nicer?", "What have you wanted to tell me but kept forgetting?"]),
      s("Plan an imaginary ordinary day", ["Describe a free day you would enjoy together, from breakfast to bedtime. Keep it within a realistic budget. Where your choices differ, get curious about the reason instead of negotiating every detail."], ["Where would we have breakfast?", "Would we go out or stay in?", "What would we each want an hour alone for?", "Which part could we actually do this weekend?"]),
      s("Trade a memory, then add a detail", ["One of you describes a shared memory. The other adds something they remember differently. Different recollections are an invitation to hear another perspective, not an accuracy contest."], ["What surprised you about our first proper conversation?", "When did we handle something well as a team?", "What tiny moment would you like to repeat?", "What did you notice that I probably missed?"]),
      s("Try an appreciation and a request", ["Each person names a specific thing they appreciated and one small request for the coming week. Keep requests achievable. This exercise is for everyday connection; a recurring conflict deserves a separate, unhurried discussion."], undefined, ["I appreciated you checking in before my presentation. Could we have a phone-free dinner this week?", "I liked our walk yesterday. I'd love to do that again, even if it's just around the block."]),
      s("When conversation feels difficult", ["You do not have to force depth every time you sit together. A walk, shared task or familiar game may make talking easier than facing each other with a list. Choose a time when neither of you is rushing.", "If one of you is upset, acknowledge it instead of covering it with cheerful prompts. Ask whether to talk now or choose another time. If you both want to discuss recurring expectations, these [relationship check-in questions](/relationship-check-in-questions) give that conversation more structure."]),
    ],
    faq: [{ q: "Are these for long-term couples?", a: "Yes. They focus on changing everyday experiences rather than facts you may already know about each other." }, { q: "Can we use them over text?", a: "Yes. Send one prompt and answer it yourself too. Save complicated disagreements for a format you both find easier." }, { q: "What if my partner does not want to participate?", a: "Ask whether another time or activity would suit them. An invitation works better than turning participation into a test of affection." }],
    related: ["questions-to-ask-your-boyfriend", "relationship-check-in-questions", "how-to-keep-a-conversation-going"],
  },
  {
    slug: "dating-intentions", keyword: "dating intentions", title: "Dating Intentions: What They Mean and How to Ask",
    description: "Understand dating intentions, ask what someone is looking for, and distinguish shared expectations from assumptions based on chemistry or frequent texts.",
    category: "Understand the relationship", question: "situationship", cta: "Review words and follow-through in your chat",
    intro: "Dating intentions describe what someone hopes to pursue: meeting people casually, exploring a possible relationship or looking for a committed partnership. They are useful starting points, but you still need to discuss what those words mean to each of you. Frequent texting does not establish exclusivity.",
    sections: [
      s("Be specific about what you want", ["Separate your general goal from a promise about this particular person. You can want a long-term relationship while still getting to know someone. Equally, a person can enjoy your company without wanting the arrangement you want."], ["What kind of connection am I available for?", "Would I be comfortable if this stayed casual?", "What would exclusivity mean to me?", "Which expectations do I need to discuss before getting more involved?"]),
      s("Ask without setting a trap", ["A clear question gives someone room to answer honestly. Choose a moment when neither of you is trying to end a conversation or rush out. Share your own intention so it does not feel like a guessing game."], undefined, ["I'm dating with the hope of finding a relationship, though I like getting to know someone first. What are you looking for?", "When you say casual, what does that mean for communication and seeing other people?"]),
      { heading: "Listen for an answer you can use", paragraphs: ["These responses do not need decoding into secret promises. Clarify the practical meaning and decide whether it works for you."], table: { headings: ["Answer", "Possible follow-up"], rows: [["‘I'm open to a relationship.’", "‘What would you need to know before deciding whether to pursue one with me?’"], ["‘I'm not ready for anything serious.’", "‘Thanks for being clear. I'm looking for something different.’"], ["‘Let's see where it goes.’", "‘I'm happy to keep learning about each other. Can we talk about exclusivity and expectations separately?’"], ["‘I don't know.’", "‘What do you feel able to offer right now?’"]] } },
      s("Revisit the conversation when circumstances change", ["An early intention is not a binding promise to develop feelings. However, changed expectations should be discussed rather than left for someone to discover. If the answer remains unclear, choose based on the arrangement available now, not the future you hope for.", "Messages can show whether plans are specific and followed through, which is also where [mixed signals](/mixed-signals-text-analyzer) usually show up. They cannot replace an agreement. If you are repeatedly rereading affectionate texts to find commitment, a direct conversation is likely to give you more useful information."]),
    ],
    faq: [{ q: "When should I ask about dating intentions?", a: "When the answer matters to your decision to keep dating. There is no universal date number you have to wait for." }, { q: "Does dating with intention mean moving quickly?", a: "No. Being clear about your aims is compatible with taking time to learn about someone." }, { q: "Can intentions change?", a: "Yes. What matters is communicating changes and letting the other person decide whether the new arrangement suits them." }],
    related: ["situationship-vs-relationship", "mixed-signals-text-analyzer", "talking-stage"],
  },
  {
    slug: "situationship-vs-relationship", keyword: "situationship vs relationship", title: "Situationship vs Relationship: What Is Actually Different?",
    description: "Compare a situationship with a defined relationship across expectations, exclusivity, plans and communication, with questions to clarify where you stand.",
    category: "Understand the relationship", question: "situationship", cta: "Look at the pattern behind your uncertainty",
    intro: "The difference between a situationship and a defined relationship is usually clarity about the arrangement, not how affectionate the messages are. A relationship involves some shared understanding of being together. A situationship leaves important expectations unsettled. Neither a label nor a daily good-morning text tells you whether your needs are being met.",
    sections: [
      { heading: "Compare agreements, not appearances", paragraphs: ["Every couple sets different expectations. This table gives you subjects to discuss, not rules that all relationships must follow. If you are still working out [what a situationship is](/situationship), start there."], table: { headings: ["Question", "Often unclear in a situationship", "Discussed in a defined relationship"], rows: [["What are we doing?", "Each person may be imagining something different.", "Both can describe the arrangement."], ["Are we exclusive?", "It may be assumed rather than agreed.", "The agreement is explicit, whatever it is."], ["How do we plan time?", "Plans may depend on convenience without shared expectations.", "People know what they can reasonably expect."], ["Can needs be discussed?", "Someone may fear that asking will end things.", "Needs can be raised even when the answer is difficult."], ["What happens next?", "The subject stays vague.", "Both can discuss whether their aims still align."]] } },
      s("What does not settle the label", ["Meeting friends, spending nights together and texting every day may feel significant. They do not automatically mean you have agreed to a committed or exclusive relationship. Conversely, using a label does not guarantee respectful treatment.", "If you are unsure, start with the unresolved agreement. ‘Are we seeing other people?’ is more actionable than trying to establish whether your chat looks sufficiently romantic. It helps to be clear about your own [dating intentions](/dating-intentions) first."]),
      s("Have a concrete conversation", ["Say what you enjoy, what you want and what you need to understand. Give the other person space to answer, but do not replace an unwelcome answer with your preferred interpretation."], undefined, ["I like spending time with you, and I'd like to explore an exclusive relationship. Is that something you want too?", "I'm comfortable taking things slowly. I'm not comfortable assuming we're on the same page without talking about it."]),
      s("Choose based on the answer", ["If your aims align, discuss what changes in practice. If they do not, you do not need to persuade someone to want the same thing. You can decide that the current arrangement no longer works for you.", "If you both need time, choose a mutually acceptable point to revisit the discussion. A check-in is useful when it leads to a real conversation, not when it continually postpones one."]),
    ],
    faq: [{ q: "Can a situationship become a relationship?", a: "It can if both people want that and agree on what changes. More effort from one person alone does not create a shared commitment." }, { q: "Is a casual relationship a situationship?", a: "Not necessarily. A casual arrangement can be clearly understood by both people; uncertainty is the central issue here." }, { q: "Can a chat analyzer tell me our status?", a: "No. It can highlight interaction patterns, but relationship status depends on what you have agreed." }],
    related: ["situationship", "dating-intentions", "situationship-analyzer"],
  },
  {
    slug: "conversation-starters-over-text", keyword: "conversation starters over text", title: "Conversation Starters Over Text, Plus What to Say Next",
    description: "Find conversation starters over text for a crush, a new date or someone you already know, with follow-up examples and ways to avoid forcing the chat.",
    category: "Better conversations", question: "likes_me", cta: "See how the conversation flows both ways",
    intro: "A useful conversation starter over text gives the other person something specific to respond to. A shared detail, a small story or a genuine question usually offers more than another ‘hey.’ Choose a message you would actually say, then leave room for a reply.",
    sections: [
      s("Start from something you already share", ["Refer to a conversation, interest or plan they have willingly shared. Being specific shows attention without pretending you know someone well before you do."], undefined, ["You were deciding which movie to watch—did you end up choosing the comedy?", "I tried the coffee place you mentioned. You were right about the pastries.", "How did your presentation go? You sounded excited about the idea.", "That trail we talked about looks great this weekend. Have you been before?"]),
      s("What to text your crush when you need an opening", ["An early conversation can be light and personal without being intense. Share a little about yourself instead of asking a chain of unrelated questions. If you want a few prompts, try these [questions to ask your crush](/questions-to-ask-your-crush)."], undefined, ["I have an important low-stakes question: best snack for a long train journey?", "I'm looking for something good to watch. What have you actually enjoyed lately?", "My attempt at cooking tonight was ambitious. Do you have a meal you can reliably make?", "What's one thing you're looking forward to this weekend?"]),
      s("Build the next turn from their answer", ["Pick a detail, respond to it, then offer something of your own. You do not need a question at the end of every message. A conversation can grow from shared observations too."], undefined, ["You: ‘What's been the highlight of your week?’", "Them: ‘Finally went climbing again.’", "You: ‘Nice! Was it the place you used to go? I've been wanting to try, though heights and I have an uneasy relationship.’"]),
      s("Move from chatting to a plan", ["If you would like to meet, a specific invitation is clearer than days of hints. Make it easy to decline or suggest another time. An accepted plan tells you more about availability than an emoji does."], undefined, ["I've enjoyed talking with you. Want to get coffee Saturday afternoon?", "No worries if this week is full. If you'd like to meet another time, let me know what works."]),
      s("When you get little back", ["One busy exchange is not a verdict. But if you repeatedly supply every topic and receive no curiosity in return, take a break from finding ever-better openings. You can ask whether another format would suit them or let the conversation rest. There are more ideas for [how to keep a conversation going](/how-to-keep-a-conversation-going) without forcing it.", "Do not use personal information from monitoring their activity as an opening. A comfortable conversation starts with interest both people can choose to return."]),
    ],
    faq: [{ q: "Is ‘hey’ a bad opener?", a: "No, but a detail or question gives the other person more to answer. Familiar partners may not need an elaborate opening." }, { q: "How soon should I send another message?", a: "There is no universal timer. Consider the context and whether a follow-up adds something useful rather than simply checking for attention." }, { q: "What if my message is left on read?", a: "Give the person room to respond. If plans need confirming, send a practical follow-up; otherwise you do not have to keep restarting the exchange." }],
    related: ["questions-to-ask-your-crush", "how-to-keep-a-conversation-going", "left-on-read"],
  },
  {
    slug: "should-i-text-my-ex", keyword: "should i text my ex", title: "Should I Text My Ex? Work Through the Decision",
    description: "Decide whether to text your ex by considering your purpose, their boundaries and the possible response. Includes practical and respectful message examples.",
    category: "Exes & uncertainty", question: "ex_came_back", cta: "Review the pattern before reconnecting",
    intro: "Before texting your ex, be clear about what the message is for and whether contact is welcome. Missing someone is understandable, but a message cannot guarantee reassurance, closure or reconciliation. Make the decision based on the relationship you had and the boundaries that exist now.",
    sections: [
      s("Start with whether contact is appropriate", ["If they asked you not to contact them, respect that. Do not use a new number, account or mutual friend to get around a block. Where necessary practical arrangements exist, use the agreed channel.", "If contact could put you at risk, you do not owe a conversation. Speak with someone you trust or a support service about safer options rather than using a chat analysis to decide whether it is safe."]),
      { heading: "Identify the job you want the text to do", paragraphs: ["Different reasons call for different choices. These are reflection prompts, not a scoring system."], table: { headings: ["Your purpose", "Before sending"], rows: [["Return belongings or settle a practical matter", "Keep it specific and use the agreed channel."], ["Apologize", "Can you take responsibility without asking for comfort or forgiveness?"], ["Explore reconciliation", "Can you name what changed, and accept that they may not want contact?"], ["Find relief from missing them", "Would writing an unsent message or talking with a friend meet that need first?"], ["Get an explanation", "Are you prepared for no reply or an answer that does not feel satisfying?"]] } },
      s("Write a message with one purpose", ["Keep practical matters separate from an emotional reopening. If you want to reconnect and contact is welcome, say so without disguising it as an accidental message."], undefined, ["I still have your jacket. Would you prefer that I leave it with Sam or arrange a time to return it?", "I've been reflecting on how things ended. If you're open to a conversation, I'd like to talk. I understand if you'd rather not."]),
      s("Decide what you will do after sending", ["Choose in advance how you will handle no response. Avoid a sequence of follow-ups designed to get a reaction. A reply may mean willingness to talk; it does not automatically mean a wish to restart the relationship.", "If reconciliation is discussed, look for concrete changes and compatible expectations. Affectionate messages can coexist with the same unresolved problems. If your ex has reached out first, [does my ex want me back](/ex-text-analyzer) looks at what their texts can and cannot tell you. You can care about someone and still decide not to resume the relationship."]),
    ],
    faq: [{ q: "Should I text my ex happy birthday?", a: "Consider whether contact is welcome and whether you are genuinely comfortable receiving no reply. A birthday is not an exception to a no-contact request." }, { q: "Should I wait a fixed number of days?", a: "A calendar cannot tell you whether contact is appropriate. Boundaries, your purpose and the circumstances matter more." }, { q: "Can I get closure without a reply?", a: "You may not receive the explanation you want. Reflecting on what happened and what you need going forward does not require their participation." }],
    related: ["ex-text-analyzer", "breadcrumbing", "mixed-signals-text-analyzer"], sources: [boundaries],
  },
];

GUIDES.push(
  {
    slug: "questions-to-ask-your-crush", keyword: "questions to ask your crush", title: "Questions to Ask Your Crush Without Making It an Interview",
    description: "Explore questions to ask your crush, from easy interests to light flirting, with follow-up ideas and respectful ways to suggest a date.",
    category: "Better conversations", question: "likes_me", cta: "Explore the interest in your conversation",
    intro: "Good questions to ask your crush help you learn whether you enjoy talking to each other. Start with something easy to answer, share your own perspective and notice whether curiosity goes both ways. You are getting to know a person, not trying to find the one question that makes them like you.",
    sections: [
      s("Easy questions when you barely know each other", ["Ask about a choice or experience rather than requesting a life story. Use what you already know to make the question feel connected to the conversation."], ["What's something you've enjoyed doing lately?", "Where would you take a friend visiting for the day?", "What's a hobby you would try if being terrible at it didn't matter?", "Do you have a comfort movie you keep coming back to?", "What's the best thing you've eaten this week?", "What do you like about the place you grew up?"]),
      s("Go a little deeper when the conversation invites it", ["Personal does not have to mean painful. Let them choose the level of detail, and do not press for information they have avoided sharing."], ["What is something you're looking forward to learning?", "When do you feel most like yourself?", "What do you admire in your closest friends?", "What changed your mind about something recently?", "What does a good weekend feel like to you?", "What's a small thing people do that makes you feel appreciated?"]),
      s("Flirty questions to ask a guy", ["Light flirting works best when the other person seems comfortable participating. Offer a playful opening without making a sexual assumption or requiring them to compliment you. These [flirting examples](/flirting-examples) show the difference between friendly and clearly interested."], ["Would you rather plan a first date or be surprised?", "What would be your very specific idea of a great date?", "Are you this funny in person too?", "If we went for coffee, which place would you choose?", "What's a tiny gesture you find unexpectedly charming?", "Should we find out whether our snack opinions are compatible in person?"]),
      s("Follow the answer instead of the list", ["If they mention loving live music, ask about a memorable show and share one of your own. That gives the conversation continuity. Switching immediately from hobbies to family to relationship goals can feel like a questionnaire."], undefined, ["Them: ‘I'd love to learn pottery.’", "You: ‘The practical kind or making beautifully strange objects? I tried once and produced a very uneven bowl.’"]),
      s("Make an invitation when you want one", ["Questions can help you connect, but they do not replace saying you would like to meet. A clear invitation lets both people choose. If the response is no, accept it without trying another line from the list. If you are still reading the signs, see [how to know if someone likes you](/does-he-like-me-text-analyzer)."], undefined, ["I've enjoyed getting to know you. Would you like to go for a walk and coffee this weekend?"]),
    ],
    faq: [{ q: "What should I avoid asking too early?", a: "Avoid demands for private history, explicit details or reassurance about your chances. Let trust and mutual interest set the pace." }, { q: "How do I know if they are flirting back?", a: "Look for voluntary engagement and follow-through, but do not treat teasing or emojis as proof. A respectful invitation is clearer than guessing indefinitely." }, { q: "What if I get nervous?", a: "Pick one question you are genuinely curious about and have your own answer ready. You do not need to sound perfectly smooth." }],
    related: ["conversation-starters-over-text", "flirting-examples", "does-he-like-me-text-analyzer"],
  },
  {
    slug: "how-to-keep-a-conversation-going", keyword: "how to keep a conversation going", title: "How to Keep a Conversation Going Without Forcing It",
    description: "Learn how to keep a conversation going through follow-up questions, shared details and natural topic changes, with examples for text and in-person chats.",
    category: "Better conversations", question: "more_invested", cta: "Look at how you both contribute",
    intro: "To keep a conversation going, respond to something the other person actually said, add a detail of your own and give them room to contribute. You do not need an endless supply of questions. A good exchange also includes pauses, changes of topic and a comfortable ending.",
    sections: [
      s("Pick one detail to follow", ["An answer usually contains several possible threads: a place, a person, a feeling or an event. Choose the one you are interested in. Specific curiosity is easier to answer than a broad request to ‘tell me more about yourself.’"], undefined, ["Them: ‘I went hiking with my sister.’", "You: ‘Was that the trail you were worried would be too steep?’", "Them: ‘Yes, but the view was worth it.’", "You: ‘That sounds satisfying. I'm good at the scenic part and less enthusiastic about the uphill bit.’"]),
      s("Share before asking again", ["If you only ask questions, the other person may feel interviewed. Share a reaction, a short story or a preference they can respond to. Keep it connected and leave enough space for them to speak.", "In person, attention also means listening without preparing your next line. Over text, it may mean answering the question they asked before introducing another subject."]),
      { heading: "Give a flat exchange somewhere to go", paragraphs: ["The aim is not to produce a cleverer script. Add enough detail for the other person to choose a thread. If replies stay one word no matter what you send, read about [dry texting](/dry-texting)."], table: { headings: ["Conversation stalls", "A more open next turn"], rows: [["‘Work was fine.’", "‘I finally finished the part I'd been avoiding. What's been taking up your day?’"], ["‘Nice.’", "‘That sounds fun. Was it a last-minute plan?’"], ["‘What else?’", "‘You mentioned wanting to move—have you found an area you like?’"], ["Another unrelated question", "‘That reminds me of something that happened yesterday…’"]] } },
      s("Change the subject or let the chat end", ["You can say ‘On a different note’ when a topic has run its course. You can also end warmly: ‘I need to get back to work, but I enjoyed this.’ A pause does not make a conversation a failure.", "If you repeatedly do all the work, better technique may not be the missing piece. Consider timing and preferences, then notice whether the other person ever chooses to restart the conversation. A [who texts first calculator](/who-texts-first) can show whether that balance has shifted. Mutual participation matters more than keeping every exchange alive."]),
    ],
    faq: [{ q: "How do I avoid awkward silence?", a: "A short silence is normal. Give the person time to think, return to a detail they mentioned or acknowledge that you are choosing your words." }, { q: "What if they answer every question with one word?", a: "Offer a little about yourself, try another time or format, and see whether engagement changes. You are not responsible for supplying both sides." }, { q: "Should every text end with a question?", a: "No. Observations, stories and reactions can all invite a response. Constant questioning can make the exchange feel pressured." }],
    related: ["conversation-starters-over-text", "dry-texting", "who-texts-first"],
  },
  {
    slug: "left-on-read", keyword: "left on read", title: "Left on Read: What It Means and What to Do Next",
    description: "Being left on read can feel confusing. Separate what a read receipt shows from what it cannot tell you, and choose a practical next step.",
    category: "Texting patterns", question: "mixed_signals", cta: "See whether this is part of a wider pattern",
    intro: "Being left on read means a message appears to have been opened without a reply following. It does not tell you why. Before interpreting it as rejection, consider what you sent, whether an answer was needed and the person's usual way of communicating.",
    sections: [
      s("What you know, and what you are guessing", ["A read indicator is an app signal, not access to someone's attention or intentions. Someone may open a message while occupied, need time to answer or see no question to respond to. They may also be avoiding a conversation. The receipt alone does not distinguish these possibilities. If contact has stopped altogether, [what ghosting means and how to handle it](/ghosting) is a different situation.", "‘Left on delivered’ is different: the app has not shown the message as read. Neither label tells you how much someone cares. App settings and usage can affect what you see."]),
      { heading: "Choose a response that fits the message", paragraphs: ["A practical deadline calls for a different follow-up than an ordinary chat. Avoid using a fixed number of hours as a universal rule."], table: { headings: ["Situation", "Useful next step"], rows: [["You sent a reaction or ended a conversation", "Let the exchange rest; a reply may not be needed."], ["You asked a question without urgency", "Allow time and continue with your day."], ["You need to confirm a plan", "Send one clear follow-up with a practical deadline."], ["An important discussion is repeatedly ignored", "Ask for a time and format to talk, then consider whether this works for you."], ["They asked for no contact", "Respect that request; do not follow up."]] } },
      s("A follow-up that does not demand reassurance", ["Say what you need rather than asking why they were online. If there is a deadline, explain it and give a reasonable option to decline."], undefined, ["Are we still meeting tomorrow? If I don't hear by this evening, I'll make other plans.", "I'd like to talk about what I sent. Is there a better time to discuss it?"]),
      s("If this keeps happening", ["Repeatedly unanswered questions can leave you uncertain even if each individual delay has an explanation. A [reply time calculator](/reply-time-calculator) shows whether slow replies are new or have always been part of the rhythm. Describe the pattern and its effect. Ask whether your communication expectations are compatible.", "Try not to turn timestamps or social activity into a surveillance routine. You can decide that an arrangement is not working without proving a hidden motive. Chat analysis can organize a history of exchanges, but it cannot explain a person's private reason for not replying."]),
    ],
    faq: [{ q: "How long counts as being ignored?", a: "There is no universal threshold. Your usual contact, the message and any agreed deadline are better context than an arbitrary timer." }, { q: "Should I leave them on read too?", a: "You can reply when it suits you, but deliberately using silence as a punishment is unlikely to clarify what either person wants." }, { q: "Is being left on read ghosting?", a: "One unanswered message is not enough to establish ghosting. Ghosting usually refers to ending ongoing contact without an explanation." }],
    related: ["ghosting", "dry-texting", "reply-time-calculator", "mixed-signals-text-analyzer"],
  },
  {
    slug: "flirting-examples", keyword: "flirting examples", title: "Flirting Examples: Friendly, Playful or Clearly Interested?",
    description: "Compare flirting examples with friendly messages, understand the role of context, and express interest clearly without assuming it is returned.",
    category: "Understand the relationship", question: "likes_me", cta: "Put the messages in context",
    intro: "Flirting can include playful attention, personal compliments or invitations that hint at romantic interest. The same words can also be friendly. Useful flirting examples show the context and the other person's response, rather than treating a phrase or emoji as proof.",
    sections: [
      { heading: "Compare messages in context", paragraphs: ["These fictional examples move from general warmth toward clearer interest. None requires the recipient to respond romantically. If you want a way in, try these [questions to ask your crush](/questions-to-ask-your-crush)."], table: { headings: ["Friendly", "Potentially flirty", "Clearer interest"], rows: [["‘Great seeing everyone tonight.’", "‘You made tonight a lot more fun.’", "‘I enjoyed talking with you. Would you like to go on a date?’"], ["‘That photo is great.’", "‘That smile is making it hard to concentrate.’", "‘I find you attractive, and I'd like to get to know you.’"], ["‘We should all try that café.’", "‘I think you owe me a coffee rematch.’", "‘Want to get coffee, just the two of us?’"]] } },
      s("Look for room to participate", ["Playful teasing should feel enjoyable to both people. If someone changes the subject, responds neutrally or says they are uncomfortable, ease off. A teasing style is not permission to criticize, embarrass or push a boundary.", "In person, smiles and eye contact can be warm without being romantic. At work or in service settings, friendliness may be part of the interaction. Avoid interpreting ordinary politeness as a private invitation."]),
      s("Respond in a way that matches what you want", ["You can reciprocate lightly, ask for clarification or keep the exchange friendly. A clear answer is kinder than feeling obliged to play along."], undefined, ["Interested: ‘I'd like that. Are you asking me on a date?’", "Unsure: ‘I enjoy talking with you. Let's get to know each other a bit more.’", "Not interested: ‘Thank you, but I see this as a friendship.’"]),
      s("Let follow-through add information", ["A flirtatious message may express attraction in the moment. It does not establish commitment, availability or a shared goal. Notice whether an invitation becomes a plan and whether the person respects your answer.", "If the connection matters to you, asking what they want is more useful than continually grading every message. An analyzer can draw attention to patterns in your chat, but your interpretation still needs the context outside it. Asking about [dating intentions](/dating-intentions) is usually quicker."]),
    ],
    faq: [{ q: "Are heart emojis flirting?", a: "Sometimes, but people use them with friends and family too. Look at their normal usage and the wider exchange." }, { q: "Is teasing a sign of attraction?", a: "It can be, but it can also be a person's general social style. Teasing that makes you uncomfortable does not become acceptable because someone calls it flirting." }, { q: "What is the clearest way to show interest?", a: "A respectful, direct invitation makes your intention easier to understand and gives the other person a real choice." }],
    related: ["questions-to-ask-your-crush", "does-he-like-me-text-analyzer", "dating-intentions"],
  },
  {
    slug: "relationship-check-in-questions", keyword: "relationship check in questions", title: "Relationship Check-In Questions for a Useful Conversation",
    description: "Use a relationship check-in agenda to discuss appreciation, expectations, communication and one practical change, without turning the conversation into a scorecard.",
    category: "Better conversations", question: "more_invested", cta: "Bring concrete observations to your check-in",
    intro: "Relationship check-in questions help you discuss how things are going before assumptions accumulate. Choose a calm time, agree on what you want to cover and let both people speak. A useful check-in ends with understanding and a manageable next step, not a verdict on who is the better partner.",
    sections: [
      s("Agree on the conversation first", ["Ask whether now is a good time and choose a length you can both manage. If one person is tired or distracted, set another time rather than springing a serious discussion on them. You can use the questions below as an agenda and skip anything that does not apply. For lighter evenings, [conversation starters for couples](/conversation-starters-for-couples) work better."], undefined, ["Could we spend a little time this weekend talking about how things have felt lately? I'd like us both to have a say."]),
      s("Start with what is working", ["Specific appreciation helps you identify what you want to keep doing. It should be honest, not a scripted compliment before a complaint."], ["When did you feel connected to me recently?", "What have I done that helped you feel supported?", "What is something we handled well together?", "Which routine would you like us to keep?"]),
      s("Discuss effort and expectations", ["Talk about observations and needs rather than claiming to know the other person's motive. Different workloads, health and family responsibilities can change what each person can offer."], ["Does our contact rhythm work for you?", "Are there plans or responsibilities that feel unclear?", "Is there something you need more or less of from me?", "Do we have different assumptions about time together?", "How would you like us to raise a concern?", "Is there a subject we've been avoiding?"]),
      s("Choose one change you can notice", ["Translate a general request into something practical. ‘Be more thoughtful’ leaves room for different interpretations. ‘Let me know when our plan changes’ is easier to act on. Agree when to revisit the change, without policing each other in the meantime."], undefined, ["Observation: ‘Our last two plans changed at the last minute.’", "Need: ‘I need a little more notice so I can organize my evening.’", "Request: ‘Can we confirm plans the day before, and message as soon as anything changes?’"]),
      s("Pause if the discussion stops being useful", ["If you are talking over each other or becoming overwhelmed, agree to return at a specific time. A pause should not become an indefinite refusal to discuss the issue.", "A chat summary, such as the one a [WhatsApp relationship analyzer](/whatsapp-relationship-analyzer) produces, may help you find concrete examples, but avoid presenting metrics as proof that your partner owes you a feeling. The purpose is to understand each other and make choices together."]),
    ],
    faq: [{ q: "How often should couples check in?", a: "Choose a rhythm that feels useful to both of you. A regular invitation can help, but there is no required schedule." }, { q: "Can a check-in happen over text?", a: "Yes, if both people prefer that. Allow time to think and clarify tone; switch formats if messages make the discussion harder." }, { q: "What if we disagree about what happened?", a: "Separate the observable event from what it meant to each of you. You may still be able to agree on a practical change without identical interpretations." }],
    related: ["conversation-starters-for-couples", "questions-to-ask-your-boyfriend", "who-texts-first"], sources: [boundaries],
  },
  {
    slug: "texting-after-first-date", keyword: "texting after first date", title: "Texting After a First Date: What to Say and When",
    description: "Find straightforward texts to send after a first date, ways to suggest a second one, and what to do when the answer is unclear or does not come.",
    category: "Better conversations", question: "likes_me", cta: "Look at the conversation after your date",
    intro: "Texting after a first date can be simple: say what you enjoyed and, if you want to meet again, make that clear. You do not need to wait a prescribed number of days or send a perfectly calibrated message. Contact them at a time that feels considerate and natural.",
    sections: [
      s("If you would like a second date", ["Mention one real detail and offer a plan or ask about availability. Be warm without promising a relationship after one meeting. A specific invitation gives the other person something useful to answer."], undefined, ["I had a lovely time tonight. I'm still laughing about the train story. Want to get dinner next week?", "Thanks for today. I'd like to see you again—are you free Saturday afternoon?"]),
      s("If you are unsure or do not want another date", ["You can take time to think without sending enthusiasm you do not mean. If you know you do not want to continue and contact is safe, a brief clear response is kinder than keeping the possibility open for reassurance."], undefined, ["Thanks for meeting up. I enjoyed our conversation, but I don't feel the romantic connection I'm looking for. Wishing you well."]),
      s("When the answer is warm but vague", ["‘I had fun too’ is a positive response to the evening, but it does not confirm another date. Offer one concrete option. If they cannot make it, notice whether they suggest an alternative rather than treating every delay as either rejection or a secret sign. For the wider question, see [how to know if someone likes you](/does-he-like-me-text-analyzer)."], undefined, ["Would Thursday evening work? If not, let me know a day that suits you."]),
      s("If they do not reply", ["Consider whether your message clearly asked a question and whether they have had a reasonable chance to answer. A single relevant follow-up can clarify a plan. Repeated check-ins, accusations or contacting them elsewhere are unlikely to help.", "[Ghosting](/ghosting) after a first date can feel disappointing because you are left without an explanation. You may not learn why. You can stop pursuing contact without concluding that you caused it or trying to extract a response."]),
      s("Keep the next conversation proportionate", ["If you agree to meet again, you do not need to maintain nonstop texting to keep the date alive. Share what feels natural and confirm practical details. Interest has room to develop through spending time together, not only through the number of messages exchanged."]),
    ],
    faq: [{ q: "Who should text first?", a: "Either person can. Reaching out once is an expression of interest, not evidence that you are more invested in every part of the connection." }, { q: "Is texting the same night too soon?", a: "Not inherently. A brief thank-you or invitation is reasonable if you want to send it." }, { q: "Does a slow reply mean the date went badly?", a: "Not necessarily. The answer and subsequent follow-through are more informative than speed alone." }],
    related: ["conversation-starters-over-text", "ghosting", "does-he-like-me-text-analyzer"],
  },
  {
    slug: "love-bombing-vs-genuine-interest", keyword: "love bombing vs genuine interest", title: "Love Bombing vs Genuine Interest: Look at Pace and Boundaries",
    description: "Compare intense early interest with pressure and control. Look at responses to boundaries, consistency and independence rather than counting compliments.",
    category: "Understand the relationship", question: "mixed_signals", cta: "Review the words and patterns with context",
    intro: "When comparing love bombing with genuine interest, the useful distinction is not how many compliments you receive. Look at whether affection leaves you free to choose your pace, keep your independence and say no. Intensity alone cannot establish intent; pressure and responses to boundaries deserve closer attention.",
    sections: [
      { heading: "Compare what happens when you need something different", paragraphs: ["These examples are prompts for reflection, not a diagnostic test. A concerning behavior matters even if you cannot find the perfect label for it."], table: { headings: ["Situation", "Room for your choice", "Pressure to notice"], rows: [["You want to slow down", "They accept the pace and discuss it.", "They frame your pace as betrayal or proof you do not care."], ["You have plans with friends", "They respect your independent time.", "They use affection or guilt to demand that you cancel."], ["You decline a gift", "They respect your decision.", "They insist you owe access or commitment because of it."], ["You disagree", "Warmth can coexist with a different opinion.", "Affection becomes conditional on agreement."]] } },
      s("Separate excitement from an obligation", ["Early enthusiasm can be enjoyable. You are still allowed to take time, change your mind and maintain your usual commitments. A gift, declaration or long conversation does not create a debt you must repay with closeness.", "love is respect describes intense affection paired with boundary-pushing as a warning sign. Consider behavior over time and seek support if you feel pressured or controlled; a label is not required before taking your discomfort seriously."]),
      s("State your preference if it is safe to do so", ["A direct statement makes your preference clear. It should not be used as a secret experiment to provoke a reaction. If you expect intimidation or retaliation, prioritize support rather than arranging a confrontation."], undefined, ["I'm enjoying getting to know you, and I want to take this slowly. I'm keeping my plans with friends this weekend.", "I'm not comfortable with expensive gifts at this stage. Please don't buy that for me."]),
      s("Use support beyond the chat", ["Messages cannot show everything that happens in a relationship. A friendly transcript does not rule out harm, and an automated report cannot determine whether you are safe. If you feel afraid, isolated or controlled, a trusted person or a relationship-abuse support service can help you think through your options.", "For a fuller explanation of the term and what to do next, read [what love bombing is and its warning signs](/love-bombing). For everyday uncertainty without pressure, [asking about dating intentions](/dating-intentions) can help you discuss expectations."]),
    ],
    faq: [{ q: "Is saying ‘I love you’ early always love bombing?", a: "No. Timing alone does not establish it. Consider whether your response and pace are respected and whether affection is tied to demands." }, { q: "Can someone be sincere and still cross a boundary?", a: "Yes. You do not have to settle their intentions before saying a behavior is not okay for you." }, { q: "Can AI identify love bombing?", a: "AI cannot establish motive, diagnose a person or assess your safety. It may organize examples, but it should not decide whether a relationship is safe." }],
    related: ["love-bombing", "dating-intentions", "mixed-signals-text-analyzer"], sources: [bombing],
  },
);

GUIDES.push(
  {
    slug: "situationship", keyword: "situationship", title: "Situationship: Meaning, Signs and How to Find Clarity",
    description: "Understand what a situationship means, how it differs from casual dating and a relationship, and ways to discuss expectations or decide to move on.",
    category: "Understand the relationship", question: "situationship", cta: "Explore your own situationship conversations",
    intro: "A situationship is a romantic or intimate connection whose status or expectations remain unclear. You may spend time together and care about each other without agreeing on commitment, exclusivity or what happens next. The useful question is whether the arrangement works for both of you, not whether it fits a label perfectly.",
    sections: [
      s("What makes a connection feel undefined?", ["You might know how someone takes their coffee but not whether they see the connection as casual or committed. Closeness and uncertainty can exist at the same time. These observations suggest a conversation may be needed; they are not a diagnostic checklist."], ["You have different assumptions about seeing other people.", "Plans and affection exist, but discussions about expectations remain vague.", "You avoid asking for what you need because you do not know what the arrangement allows.", "One person hopes things will change while the other is comfortable as they are."]),
      s("Situationship, casual dating or friends with benefits?", ["Casual dating can be a clear, mutually chosen arrangement. Friends with benefits usually describes a friendship that also includes sexual intimacy, though the expectations still need discussing. Either can become confusing if the people involved assume different things.", "A situationship describes that uncertainty more than a particular schedule or level of intimacy. Spending every weekend together does not establish exclusivity, and seeing each other less often does not make a defined relationship less real. For a side-by-side comparison, see [situationship vs relationship](/situationship-vs-relationship)."]),
      s("Ask yourself what you want now", ["Separate what is happening from what you hope it will become. If the arrangement stayed the same, would you still choose it? You do not need to prove the other person has done something wrong to decide you want more clarity or a different connection. If you want to see what your own chat shows, a [situationship analyzer](/situationship-analyzer) can lay out who initiates and whether plans happen."], ["Am I enjoying the arrangement as it is?", "Have I stated what I want, rather than hinted at it?", "Can I hear an honest answer even if it disappoints me?", "What am I willing and unwilling to continue?"]),
      s("Have the conversation you keep rehearsing", ["Choose a direct, specific question. Avoid relying on a dramatic deadline or pretending you do not care. Ask what the person wants and discuss the practical meaning of the answer."], undefined, ["I enjoy being with you, and I'm looking for an exclusive relationship. How do you see this?", "I don't want to keep assuming we're headed in the same direction. What do you want from this connection?"]),
      s("Continue, change the arrangement or leave", ["If you want the same thing, agree on what changes. If you do not, you can end the connection without convincing them to share your goal. ‘I care about you, but this arrangement isn't right for me’ can be enough.", "Getting over a situationship can still take time. The absence of a label does not erase your investment. Give yourself space from repeated checking and lean on people and routines that support you. You do not need an AI report to justify choosing a clearer arrangement."]),
    ],
    faq: [{ q: "How long can a situationship last?", a: "There is no fixed duration. What matters is whether both people understand and choose the arrangement rather than one person waiting indefinitely for an unpromised change." }, { q: "Can there be feelings in a situationship?", a: "Yes. Feelings and a shared commitment are different things, which is why talking about expectations matters." }, { q: "How do I end a situationship?", a: "If safe, state that the arrangement no longer works for you and be clear about the contact you want afterward. You do not need a formal relationship label to set a boundary." }],
    related: ["situationship-vs-relationship", "dating-intentions", "situationship-analyzer", "breadcrumbing"],
  },
  {
    slug: "ghosting", keyword: "ghosting", title: "Ghosting: What It Means and How to Handle Lost Contact",
    description: "Learn what ghosting means in dating, how it differs from a delayed reply or a stated boundary, and how to respond without chasing an explanation.",
    category: "Exes & uncertainty", question: "energy_changed", cta: "Review how communication changed",
    intro: "Ghosting in dating usually means stopping an ongoing connection without explaining that contact is ending. One late reply is not enough to establish it. The context is the previous relationship and a sustained absence of response where continued contact had reasonably been expected.",
    sections: [
      { heading: "Distinguish silence from a clear ending", paragraphs: ["You may not know why someone has stopped responding. You can still distinguish what was communicated from what remains unanswered. One unanswered message is closer to being [left on read](/left-on-read) than to ghosting."], table: { headings: ["Situation", "What it tells you"], rows: [["‘I'm offline this week; let's talk Sunday.’", "A communicated pause, provided the pattern broadly matches it."], ["One message has not been answered", "Too little information to determine that contact has ended."], ["Ongoing contact stops and attempts to reconnect go unanswered", "This can fit what people mean by ghosting."], ["‘I don't want to keep dating.’", "A clear ending, even if it is disappointing."], ["‘Please don't contact me again.’", "A boundary to respect, not an invitation to seek a response."]] } },
      s("Why people ghost—and what you cannot know", ["People stop responding for different reasons, including avoiding an uncomfortable conversation, losing interest or dealing with circumstances you cannot see. Speculating about the reason can keep you stuck without giving you reliable information.", "Leaving contact without explanation can hurt. At the same time, someone who fears harassment or harm may need to stop contact without further discussion. Nobody is required to keep communicating at the expense of their safety."]),
      s("Decide whether one check-in is useful", ["If contact was welcome and there has been a genuine change, one clear message can ask where things stand. If you already sent several unanswered messages or received a no-contact request, another channel is not the answer."], undefined, ["I haven't heard from you and I'm not sure whether you'd like to keep seeing each other. If not, I'd appreciate knowing. I'll leave the next step with you."]),
      s("Make a decision without an explanation", ["You cannot make someone provide closure. You can stop holding space for an unconfirmed plan, mute a conversation that keeps pulling your attention back and ask friends for support without recruiting them to contact the person.", "Their silence is information about what contact is currently available. It is not a complete explanation of their feelings or a measure of your worth. You can move forward while some questions remain unanswered."]),
      s("If they return later", ["A new message does not erase the interruption, and repeated disappearing and returning can become [breadcrumbing](/breadcrumbing). If you want to respond, ask what happened and what would be different. Notice whether the answer acknowledges the effect on you and leads to reliable behavior. You can also decline to restart contact."]),
    ],
    faq: [{ q: "How many days count as ghosting?", a: "There is no universal number. Consider your established contact, any communicated circumstances and whether practical attempts to clarify have gone unanswered." }, { q: "Should I send a final message?", a: "You can if contact is welcome and it helps you state your decision, but you do not need their acknowledgment to stop pursuing the connection." }, { q: "Do ghosters always come back?", a: "No. There is no dependable rule about whether someone will return. Make plans around the contact you have now." }],
    related: ["left-on-read", "texting-after-first-date", "breadcrumbing", "ex-text-analyzer"],
  },
  {
    slug: "breadcrumbing", keyword: "breadcrumbing", title: "Breadcrumbing Meaning: What It Is and How to Set Boundaries",
    description: "What breadcrumbing means in dating, how it differs from being busy or casual, and how to ask for clarity or set a boundary you can keep.",
    category: "Understand the relationship", question: "mixed_signals", cta: "Compare warmth with follow-through",
    intro: "Breadcrumbing is a common dating term for intermittent attention that keeps a connection going without developing into the relationship or contact one person expects. Warm messages may repeatedly appear when you pull away, while concrete plans remain elusive. The label describes a perceived pattern; it cannot prove someone's motive.",
    sections: [
      s("Look at what repeats", ["An isolated cancelled plan or an occasional friendly message is not enough. The concern is a continuing gap between what the contact seems to promise and what is actually available. You may feel repeatedly drawn back into waiting. The [breadcrumbing examples and self-check](/breadcrumbing-test) page shows what this looks like in real text exchanges."], ["Affection restarts after a long gap, but no plan follows.", "A direct invitation receives warmth instead of an answer.", "Discussions about expectations are repeatedly deferred.", "You keep treating a new message as evidence that the arrangement has changed."]),
      s("Busy, casual or keeping things vague?", ["A busy person may be unable to meet but can sometimes name that limitation clearly. A casual connection can also be honest and mutually enjoyable. The key question is whether you both understand the arrangement and whether words align with what is offered.", "Someone may be uncertain rather than deliberately manipulative. You do not need to resolve that motive before deciding that intermittent contact is not enough for you. Focus on the behavior you experience and the relationship you want."]),
      s("Ask for the information you are missing", ["Turn a vague exchange into a concrete question. Avoid trying to make the person jealous or withdrawing as a test. State what you are available for and let their answer inform your choice."], undefined, ["It's nice to hear from you. Are you interested in making a plan to meet, or are you looking for occasional chats?", "I like you, but the on-and-off contact isn't working for me. I'm looking for something more consistent."]),
      s("Set a boundary you can act on", ["A boundary describes what you will do, not a strategy to make someone choose you. You might stop accepting last-minute plans, stop continuing flirty exchanges without clarity or end contact. Choose what suits your needs and circumstances.", "If they make a new promise, look for follow-through before assuming the pattern is different. You are allowed to decline even if the latest message is affectionate. For side-by-side text examples, [these breadcrumbing examples](/breadcrumbing-test) examine specific exchanges."]),
    ],
    faq: [{ q: "Is breadcrumbing always intentional?", a: "You usually cannot know intent from messages alone. The pattern can still be disappointing or incompatible with your needs." }, { q: "How is breadcrumbing different from ghosting?", a: "Ghosting usually involves contact stopping. Breadcrumbing involves intermittent contact that sustains expectation without dependable progress." }, { q: "Can I ask them to change?", a: "You can clearly state what you want. Whether they want and can offer it is their choice; repeated persuasion is not an agreement." }],
    related: ["breadcrumbing-test", "ghosting", "situationship", "dating-intentions"],
  },
  {
    slug: "talking-stage", keyword: "talking stage", title: "The Talking Stage: Meaning, Expectations and Next Steps",
    description: "Understand the talking stage, discuss exclusivity and texting expectations, and decide whether to move toward dating or end the connection clearly.",
    category: "Understand the relationship", question: "likes_me", cta: "Explore how your early conversations are developing",
    intro: "The talking stage is an informal term for getting to know someone with possible romantic interest before the relationship is clearly defined. It might involve messages, calls or dates. Because people use the term differently, you should not assume it includes exclusivity or a promise to become a couple.",
    sections: [
      s("What are you each exploring?", ["One person may see the talking stage as casual conversation; another may already be focusing on a possible partner. Ask what the connection means before relying on a shared label.", "Pay attention to whether you enjoy each other, can ask questions comfortably and follow through on plans. Constant messaging can create familiarity, but it does not replace learning how you relate in different situations."]),
      s("How long should the talking stage last?", ["There is no universal deadline. Distance, schedules and how you met can affect the pace. The more useful question is whether you are learning about each other and whether the arrangement remains comfortable.", "If you want to meet or define the connection, say so. You do not have to wait for an invisible milestone, and the other person does not have to want the same next step. A clear mismatch gives you useful information. Talking about [dating intentions](/dating-intentions) early makes that easier."]),
      s("Discuss texting and exclusivity separately", ["Daily messages do not automatically mean you are exclusive. Likewise, fewer messages do not necessarily mean indifference. Agree on what matters to you rather than borrowing a set of dating rules."], undefined, ["I'm enjoying this. Would you like to go on a date next week?", "Are you getting to know other people at the moment? I'd like us to be clear about our expectations.", "I don't text much while working, but I'd like to catch up in the evening."]),
      s("Notice whether the connection has room to develop", ["Look for mutual curiosity, respect when you are unavailable, and plans that become real. Be cautious about pressure to disclose, commit or remain constantly reachable. You can slow down even when you like someone.", "If every attempt to meet or discuss expectations disappears into vague reassurance, decide whether the arrangement as it stands works for you. More messaging alone does not resolve incompatible intentions, and a talking stage that never defines itself can turn into a [situationship](/situationship)."]),
      s("End it clearly when you know", ["If safe and appropriate, a brief message can close the loop without criticizing the person or leaving a false possibility open. You do not need to keep talking because you invested time."], undefined, ["I've enjoyed getting to know you, but I don't think this is the connection I'm looking for. I wanted to be clear rather than fade out."]),
    ],
    faq: [{ q: "Is the talking stage the same as dating?", a: "People use the terms differently. Some include early dates; others mean messaging before meeting. Ask about the practical expectations." }, { q: "Should we text every day?", a: "Only if that works for both of you. Frequency is not a universal measure of interest or a substitute for clear plans." }, { q: "Is it okay to talk to other people?", a: "Do not assume exclusivity has been agreed. Discuss it honestly and give the other person room to decide whether the arrangement suits them." }],
    related: ["dating-intentions", "questions-to-ask-your-crush", "texting-after-first-date", "situationship-vs-relationship"],
  },
  {
    slug: "love-bombing", keyword: "love bombing", title: "Love Bombing: Meaning, Warning Signs and Finding Support",
    description: "Understand love bombing and why pressure, control and responses to boundaries matter more than the number of affectionate messages or gifts.",
    category: "Understand the relationship", question: "mixed_signals", cta: "Understand what chat analysis can and cannot show",
    intro: "Love bombing commonly describes overwhelming affection or attention used alongside pressure or control. It can look flattering at first, but the concern is whether you remain free to set your pace and boundaries. Enthusiasm, gifts or early declarations alone cannot establish that someone is love bombing you.",
    sections: [
      s("Notice pressure beneath the attention", ["love is respect identifies boundary-pushing within intense affection as a warning sign. Consider how the person responds when you need space or disagree, rather than counting how many times they say they love you."], ["Affection comes with demands for constant access to you.", "You feel rushed into commitments you are not ready for.", "Gifts are later treated as a reason you owe something.", "Your independent plans trigger guilt, pressure or hostility."]),
      s("An example of the difference", ["The following exchange is fictional. It illustrates why the response to a preference can matter more than the original affectionate message. It does not establish a diagnosis."], undefined, ["You: ‘I'm seeing my friends tonight. Let's talk tomorrow.’", "Room for choice: ‘Have fun. I'd like that.’", "Pressure: ‘After everything I've done for you, you'd rather see them? If you loved me, you'd cancel.’"]),
      s("Take discomfort seriously without diagnosing someone", ["You do not need to establish a personality disorder or prove an intention before deciding a behavior is unacceptable. Write down what happened in plain terms if that helps you think: what was requested, what you said and what followed.", "Consider what is happening outside messages too. A chat export may leave out calls, in-person interactions, access to your accounts or other behavior that changes the situation. A warm tone in writing does not establish safety."]),
      s("Choose support that fits your situation", ["If you feel comfortable and safe, you can state what pace and contact work for you. You do not need to stage a confrontation to test the person's reaction. If you feel afraid or controlled, consider speaking with a trusted person or a specialist support service before deciding how to respond.", "The linked love is respect resource explains warning signs and offers ways to seek support. If you are in immediate danger, contact local emergency services when it is safe to do so. You are not required to provide one more explanation before seeking help."]),
      s("What a chat analyzer cannot decide", ["WhatHeThinks may organize communication patterns, but it cannot determine someone's motive, diagnose abuse or tell you whether a relationship is safe. Do not use a reassuring automated result to dismiss your own experience.", "If your question is about intense but respectful early interest, the guide to [love bombing vs genuine interest](/love-bombing-vs-genuine-interest) offers examples focused on pace, boundaries and follow-through. Neither page is a test that awards a partner a safe or unsafe score."]),
    ],
    faq: [{ q: "Is love bombing a diagnosis?", a: "No. It is a term used to describe a pattern of behavior, not a diagnosis you can establish from a chat." }, { q: "Are expensive gifts a warning sign by themselves?", a: "A gift alone does not establish the pattern. Whether it comes with pressure, obligations or disregard for your wishes matters." }, { q: "Should I confront the person?", a: "You do not have to. If you feel afraid or expect retaliation, seek support and consider your safety before deciding whether or how to communicate." }],
    related: ["love-bombing-vs-genuine-interest", "dating-intentions", "mixed-signals-text-analyzer"], sources: [bombing, { title: "love is respect: When boundaries aren't respected", url: "https://www.loveisrespect.org/resources/when-boundaries-arent-respected/" }],
  },
);

export function getGuide(slug: string) { return GUIDES.find(g => g.slug === slug); }
